version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: product_management_db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: product_management
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
